image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:

  - java -jar ./artefacts/app-order.jar & sleep 10
  - chmod +x gradlew

build_script:
  - ./gradlew test --info -Dselenide.headless=true